import type { PublicQuestion, PublicQuestionnaire } from "@/lib/types";

export const defaultQuestions: PublicQuestion[] = [
  {
    id: "need",
    key: "business_need",
    type: "multi_choice",
    label: {
      en: "What would help your business most right now?",
      hi: "अभी आपके बिज़नेस को सबसे ज़्यादा किस मदद की ज़रूरत है?",
      gu: "અત્યારે તમારા બિઝનેસને સૌથી વધુ કઈ મદદ જોઈએ છે?",
    },
    helpText: {
      en: "Choose up to 3. It’s okay if you’re not sure.",
      hi: "अधिकतम 3 विकल्प चुनें। पक्का नहीं पता तो भी कोई बात नहीं।",
      gu: "વધુમાં વધુ 3 વિકલ્પ પસંદ કરો. ખાતરી ન હોય તો પણ ચાલશે.",
    },
    placeholder: { en: "", hi: "", gu: "" },
    required: true,
    position: 1,
    options: [
      {
        id: "more_enquiries",
        label: {
          en: "More calls & WhatsApp enquiries",
          hi: "ज़्यादा calls और WhatsApp enquiries",
          gu: "વધુ calls અને WhatsApp enquiries",
        },
        description: {
          en: "For services, shops, property, education and more",
          hi: "Services, दुकान, property, education और दूसरे बिज़नेस के लिए",
          gu: "Services, દુકાન, property, education અને બીજા બિઝનેસ માટે",
        },
      },
      {
        id: "more_online_sales",
        label: {
          en: "More online product orders",
          hi: "ज़्यादा online product orders",
          gu: "Products ના વધુ online orders",
        },
        description: {
          en: "Sell products through ads and your online store",
          hi: "Ads और online store से अपने products बेचें",
          gu: "Ads અને તમારી online shop થી products વેચો",
        },
      },
      {
        id: "google_visibility",
        label: {
          en: "Show up higher on Google",
          hi: "Google पर ऊपर दिखें",
          gu: "Google પર ઉપર દેખાઓ",
        },
        description: {
          en: "Help nearby and relevant customers find you",
          hi: "आस-पास के सही ग्राहक आपको आसानी से ढूँढ सकें",
          gu: "નજીકના યોગ્ય customers તમને સરળતાથી શોધી શકે",
        },
      },
      {
        id: "creative_content",
        label: {
          en: "Better product photos, posts & videos",
          hi: "बेहतर product photos, posts और videos",
          gu: "વધુ સારા product photos, posts અને videos",
        },
        description: {
          en: "Social posts, product-page images, UGC and showcase videos",
          hi: "Social posts, product-page images, UGC और showcase videos",
          gu: "Social posts, product-page images, UGC અને showcase videos",
        },
      },
      {
        id: "shopify_store",
        label: {
          en: "Build or improve an online shop",
          hi: "Online shop बनाएँ या बेहतर करें",
          gu: "Online shop બનાવો અથવા સુધારો",
        },
        description: {
          en: "A fast, easy-to-use Shopify website",
          hi: "तेज़ और आसानी से चलने वाली Shopify Website",
          gu: "ઝડપી અને સરળ Shopify Website",
        },
      },
      {
        id: "need_guidance",
        label: {
          en: "Not sure — please guide me",
          hi: "पक्का नहीं — कृपया सही रास्ता बताएँ",
          gu: "ખાતરી નથી — મને માર્ગદર્શન આપો",
        },
        description: {
          en: "Tell us your problem and we’ll suggest the right path",
          hi: "अपनी परेशानी बताएँ, हम सही रास्ता सुझाएँगे",
          gu: "તમારી સમસ્યા જણાવો, અમે યોગ્ય રસ્તો સૂચવીશું",
        },
      },
    ],
    config: { minSelections: 1, maxSelections: 3 },
    isActive: true,
  },
  {
    id: "business-type",
    key: "business_type",
    type: "single_choice",
    label: {
      en: "What kind of business do you run?",
      hi: "आप किस तरह का बिज़नेस चलाते हैं?",
      gu: "તમારો બિઝનેસ કયા પ્રકારનો છે?",
    },
    helpText: {
      en: "Pick the closest match.",
      hi: "जो सबसे सही लगे, उसे चुनें।",
      gu: "સૌથી નજીકનો વિકલ્પ પસંદ કરો.",
    },
    placeholder: { en: "", hi: "", gu: "" },
    required: true,
    position: 2,
    options: [
      {
        id: "products",
        label: {
          en: "I sell products",
          hi: "मैं products बेचता/बेचती हूँ",
          gu: "હું products વેચું છું",
        },
        description: {
          en: "Clothing, jewellery, food, manufacturing, etc.",
          hi: "कपड़े, jewellery, food, manufacturing आदि",
          gu: "કપડાં, jewellery, food, manufacturing વગેરે",
        },
      },
      {
        id: "services",
        label: {
          en: "I provide a service",
          hi: "मैं services देता/देती हूँ",
          gu: "હું service આપું છું",
        },
        description: {
          en: "Consulting, clinic, education, property, salon, etc.",
          hi: "Consulting, clinic, education, property, salon आदि",
          gu: "Consulting, clinic, education, property, salon વગેરે",
        },
      },
      {
        id: "local_store",
        label: {
          en: "I run a shop or local business",
          hi: "मेरी दुकान या local बिज़नेस है",
          gu: "મારી દુકાન અથવા local બિઝનેસ છે",
        },
        description: {
          en: "Retail shop, restaurant, showroom, distributor, etc.",
          hi: "Retail shop, restaurant, showroom, distributor आदि",
          gu: "Retail shop, restaurant, showroom, distributor વગેરે",
        },
      },
      {
        id: "other",
        label: { en: "Something else", hi: "कुछ और", gu: "બીજું કંઈક" },
        description: {
          en: "No problem—we’ll understand it on the call",
          hi: "कोई बात नहीं — call पर समझ लेंगे",
          gu: "કોઈ વાંધો નહીં — call પર સમજી લઈશું",
        },
      },
    ],
    config: {},
    isActive: true,
  },
  {
    id: "stage",
    key: "business_stage",
    type: "single_choice",
    label: {
      en: "Where is your business today?",
      hi: "अभी आपका बिज़नेस किस स्थिति में है?",
      gu: "અત્યારે તમારો બિઝનેસ કયા તબક્કે છે?",
    },
    helpText: { en: "", hi: "", gu: "" },
    placeholder: { en: "", hi: "", gu: "" },
    required: true,
    position: 3,
    options: [
      {
        id: "starting",
        label: { en: "Just starting", hi: "अभी शुरू कर रहा/रही हूँ", gu: "હમણાં જ શરૂ કર્યું છે" },
      },
      {
        id: "running_slow",
        label: { en: "Running, but growth is slow", hi: "बिज़नेस चल रहा है, लेकिन growth धीमी है", gu: "બિઝનેસ ચાલુ છે, પણ ધીમે વધે છે" },
      },
      {
        id: "ready_to_scale",
        label: { en: "Doing well and ready to grow", hi: "बिज़नेस अच्छा चल रहा है, अब आगे बढ़ाना है", gu: "બિઝનેસ સારો ચાલે છે, હવે વધુ વધારવો છે" },
      },
    ],
    config: {},
    isActive: true,
  },
  {
    id: "budget",
    key: "monthly_budget",
    type: "single_choice",
    label: {
      en: "What monthly amount feels comfortable for growth?",
      hi: "बिज़नेस बढ़ाने के लिए हर महीने कितना budget आपके लिए ठीक है?",
      gu: "બિઝનેસ વધારવા દર મહિને કેટલું budget રાખી શકો?",
    },
    helpText: {
      en: "This helps us suggest something realistic. It is not a payment.",
      hi: "इससे हम आपके budget के हिसाब से सही plan बता पाएँगे। यह कोई payment नहीं है।",
      gu: "આ જવાબથી અમે તમારા budget મુજબનો સાચો plan સૂચવી શકીશું. આ કોઈ payment નથી.",
    },
    placeholder: { en: "", hi: "", gu: "" },
    required: true,
    position: 4,
    options: [
      { id: "under_20k", label: { en: "Under ₹20,000", hi: "₹20,000 से कम", gu: "₹20,000થી ઓછું" } },
      { id: "20k_50k", label: { en: "₹20,000 – ₹50,000", hi: "₹20,000 – ₹50,000", gu: "₹20,000 – ₹50,000" } },
      { id: "50k_1l", label: { en: "₹50,000 – ₹1 lakh", hi: "₹50,000 – ₹1 लाख", gu: "₹50,000 – ₹1 લાખ" } },
      { id: "1l_plus", label: { en: "₹1 lakh or more", hi: "₹1 लाख या अधिक", gu: "₹1 લાખ અથવા વધુ" } },
      { id: "discuss", label: { en: "Not sure — let’s discuss", hi: "पक्का नहीं — बात करके तय करेंगे", gu: "ખાતરી નથી — વાત કરીને નક્કી કરીએ" } },
    ],
    config: {},
    isActive: true,
  },
  {
    id: "timeline",
    key: "start_timeline",
    type: "single_choice",
    label: {
      en: "When would you like to start?",
      hi: "आप कब शुरू करना चाहते हैं?",
      gu: "તમે કામ ક્યારે શરૂ કરવા માંગો છો?",
    },
    helpText: { en: "", hi: "", gu: "" },
    placeholder: { en: "", hi: "", gu: "" },
    required: true,
    position: 5,
    options: [
      { id: "now", label: { en: "As soon as possible", hi: "जितनी जल्दी हो सके", gu: "જેટલું જલ્દી બને તેટલું" } },
      { id: "month", label: { en: "Within 30 days", hi: "30 दिनों के अंदर", gu: "30 દિવસની અંદર" } },
      { id: "later", label: { en: "Just exploring for now", hi: "अभी सिर्फ़ जानकारी ले रहा/रही हूँ", gu: "હમણાં માત્ર જાણકારી જોઈએ છે" } },
    ],
    config: {},
    isActive: true,
  },
  {
    id: "name",
    key: "full_name",
    type: "short_text",
    label: { en: "What should we call you?", hi: "हम आपको किस नाम से बुलाएँ?", gu: "તમારું નામ શું છે?" },
    helpText: { en: "", hi: "", gu: "" },
    placeholder: { en: "Type your full name", hi: "अपना पूरा नाम लिखें", gu: "તમારું પૂરું નામ લખો" },
    required: true,
    position: 6,
    options: [],
    config: { minLength: 2, maxLength: 100 },
    isActive: true,
  },
  {
    id: "phone",
    key: "phone",
    type: "phone",
    label: { en: "Your WhatsApp number?", hi: "आपका WhatsApp नंबर क्या है?", gu: "તમારો WhatsApp નંબર શું છે?" },
    helpText: {
      en: "We’ll only use this to discuss your enquiry.",
      hi: "हम इसका इस्तेमाल सिर्फ़ आपकी enquiry पर बात करने के लिए करेंगे।",
      gu: "તમારી enquiry વિશે વાત કરવા માટે જ આ નંબર વાપરીશું.",
    },
    placeholder: { en: "10-digit mobile number", hi: "10 अंकों का mobile number", gu: "10 અંકનો mobile number" },
    required: true,
    position: 7,
    options: [],
    config: {},
    isActive: true,
  },
  {
    id: "city",
    key: "city",
    type: "short_text",
    label: { en: "Which city is your business in?", hi: "आपका बिज़नेस किस शहर में है?", gu: "તમારો બિઝનેસ કયા શહેરમાં છે?" },
    helpText: { en: "", hi: "", gu: "" },
    placeholder: { en: "Example: Surat", hi: "उदाहरण: सूरत", gu: "ઉદાહરણ: સુરત" },
    required: true,
    position: 8,
    options: [],
    config: { minLength: 2, maxLength: 100 },
    isActive: true,
  },
  {
    id: "challenge",
    key: "biggest_challenge",
    type: "long_text",
    label: {
      en: "Anything else you want us to understand?",
      hi: "क्या आप हमें कुछ और बताना चाहते हैं?",
      gu: "બીજું કંઈ અમને જણાવવા માંગો છો?",
    },
    helpText: {
      en: "Optional — write in any language.",
      hi: "ज़रूरी नहीं — किसी भी भाषा में लिखें।",
      gu: "ફરજિયાત નથી — કોઈપણ ભાષામાં લખી શકો છો.",
    },
    placeholder: {
      en: "Example: We get enquiries but very few people buy...",
      hi: "उदाहरण: Enquiries आती हैं, लेकिन खरीदने वाले बहुत कम हैं…",
      gu: "ઉદાહરણ: enquiries આવે છે, પણ ખરીદનાર બહુ ઓછા મળે છે...",
    },
    required: false,
    position: 9,
    options: [],
    config: { maxLength: 1000 },
    isActive: true,
  },
];

export const fallbackQuestionnaire: PublicQuestionnaire = {
  formId: "11111111-1111-4111-8111-111111111111",
  versionId: "22222222-2222-4222-8222-222222222222",
  slug: "growth-check",
  name: "Global Surat Growth Check",
  version: 1,
  questions: defaultQuestions,
  isFallback: true,
};
